export const ICP_TO_DENUE: Record<string, string> = {
  'aerolineas y aviacion': 'Transportes, correos y almacenamiento',
  'agroindustria': 'Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza',
  'agropecuario': 'Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza',
  'alimentos y bebidas': 'Industrias manufactureras',
  'armadoras': 'Industrias manufactureras',
  'aseguradoras': 'Servicios financieros y de seguros',
  'automotriz': 'Industrias manufactureras',
  'bebidas alcoholicas': 'Industrias manufactureras',
  'bienes raices': 'Servicios inmobiliarios y de alquiler',
  'casinos': 'Servicios de esparcimiento culturales y deportivos',
  'cementeras': 'Industrias manufactureras',
  'centros comerciales': 'Servicios inmobiliarios y de alquiler',
  'cines': 'Información en medios masivos',
  'comercio electronico': 'Comercio al por menor',
  'construccion': 'Construcción',
  'consultoria y servicios profesionales': 'Servicios profesionales, científicos y técnicos',
  'consumo masivo (fmcg)': 'Comercio al por menor',
  'cuidado personal y belleza': 'Comercio al por menor',
  'dooh networks': 'Información en medios masivos',
  'deportes y recreacion': 'Servicios de esparcimiento culturales y deportivos',
  'e-commerce (gran volumen)': 'Comercio al por menor',
  'educacion': 'Servicios educativos',
  'energia y servicios publicos': 'Generación y distribución de energía eléctrica',
  'energias renovables': 'Generación y distribución de energía eléctrica',
  'entretenimiento': 'Servicios de esparcimiento culturales y deportivos',
  'farma y salud': 'Servicios de salud y de asistencia social',
  'farmaceuticas': 'Industrias manufactureras',
  'ferreteria': 'Comercio al por menor',
  'fibras': 'Servicios inmobiliarios y de alquiler',
  'financiera': 'Servicios financieros y de seguros',
  'fintech / banca digital': 'Servicios financieros y de seguros',
  'gobierno': 'Actividades legislativas, gubernamentales y de impartición de justicia',
  'gobierno y sector publico': 'Actividades legislativas, gubernamentales y de impartición de justicia',
  'grupos hospitalarios': 'Servicios de salud y de asistencia social',
  'hotelera y viajes': 'Servicios de alojamiento temporal y preparación de alimentos',
  'hoteles': 'Servicios de alojamiento temporal y preparación de alimentos',
  'infraestructura': 'Construcción',
  'inmobiliarias': 'Servicios inmobiliarios y de alquiler',
  'laboratorios farmaceuticos': 'Industrias manufactureras',
  'logistica / scm (b2b critico)': 'Transportes, correos y almacenamiento',
  'manufactura ligera (turnos fijos)': 'Industrias manufactureras',
  'medios y entretenimiento': 'Información en medios masivos',
  'movilidad y transporte': 'Transportes, correos y almacenamiento',
  'parques de diversiones': 'Servicios de esparcimiento culturales y deportivos',
  'petroleo y gas': 'Minería',
  'plataformas de viajes': 'Información en medios masivos',
  'procesadores de pagos': 'Servicios financieros y de seguros',
  'restaurantes': 'Servicios de alojamiento temporal y preparación de alimentos',
  'restaurantes y qrs': 'Servicios de alojamiento temporal y preparación de alimentos',
  'retail': 'Comercio al por menor',
  'salud': 'Servicios de salud y de asistencia social',
  'salud / farmaceutico (gestion)': 'Servicios de salud y de asistencia social',
  'seguros': 'Servicios financieros y de seguros',
  'servicios financieros': 'Servicios financieros y de seguros',
  'servicios de suscripcion (saas b2b)': 'Información en medios masivos',
  'software y tecnologia': 'Información en medios masivos',
  'startups': 'Información en medios masivos',
  'tecnologia': 'Información en medios masivos',
  'telecomunicaciones': 'Información en medios masivos',
  'textil': 'Industrias manufactureras',
  'trade marketing (btl)*': 'Servicios profesionales, científicos y técnicos',
  'transporte y logistica': 'Transportes, correos y almacenamiento',
  'turismo y hospitalidad': 'Servicios de alojamiento temporal y preparación de alimentos',
  'turistica': 'Servicios de alojamiento temporal y preparación de alimentos',
  'ventas directas (cambaceo)*': 'Comercio al por menor',
};

export const DENUE_TO_ICP: Record<string, string[]> = Object.entries(ICP_TO_DENUE).reduce((acc, [icp, denue]) => {
  if (!acc[denue]) acc[denue] = [];
  if (!acc[denue].includes(icp)) acc[denue].push(icp);
  return acc;
}, {} as Record<string, string[]>);
